// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production" | "development";
	MAX_BATCHES: "6" | "2";
	TARGET_RESULTS: "25";
	SEARCH_JOB: DurableObjectNamespace<import("./src/index").SearchJobDO>;
}
